# Generated by Django 3.1.2 on 2021-01-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20201209_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AUTORE_CG',
            new_name='Autore',
        ),
        migrations.RenameModel(
            old_name='GENERE_CG',
            new_name='Genere',
        ),
        migrations.RenameModel(
            old_name='LIBRO_CG',
            new_name='Libro',
        ),
    ]
